#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh
feh --bg-fill /home/nswitsu/Pictures/komi.jpg
picom --experimental-backends &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5

bspc config window_gap          10

bspc config border_width			   0
# bspc config normal_border_color		 '#430d8f'
# bspc config active_border_color		 '#6728bf'
# bspc config focused_border_color	 '#984FFF'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


