#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh
feh --bg-fill /home/nswitsu/Pictures/agr-wallpaper.png
picom --experimental-backends &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d あ な た は ば か で す

bspc config window_gap          10

bspc config border_width         3
bspc config normal_border_color		 '#e06c75'
bspc config active_border_color		 '#98c379'
bspc config focused_border_color	 '#61afef'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^3' state=floating follow=on
bspc rule -a steam desktop='^2' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


